#nullable enable

using UnityEditor;
using UnityEditor.AssetImporters;
using UnityEngine;

namespace Yohawing.MmdUnity.Editor
{
    [CustomEditor(typeof(MmdPmxScriptedImporter))]
    public sealed class MmdPmxScriptedImporterEditor : ScriptedImporterEditor
    {
        private SerializedProperty? importScaleProperty;
        private SerializedProperty? modelPresetProperty;
        private SerializedProperty? meshGenerationModeProperty;
        private SerializedProperty? materialTexturePolicyProperty;
        private SerializedProperty? shaderPresetProperty;
        private SerializedProperty? materialRemapsProperty;
        private SerializedProperty? animationTypeProperty;
        private MmdPmxAsset? cachedAsset;
        private bool onDemandRemapExpanded = true;
        private bool rigAdvancedExpanded;

        private bool toonShaderSettingsExpanded = true;
        private bool toonBasicExpanded = true;
        private bool toonShadingExpanded = true;
        private bool toonOutlineExpanded = true;
        private bool toonAdvancedExpanded = true;

        private bool materialTexturePersistencePolicyExpanded = true;

        private int selectedTab;
        private static readonly string[] TabNames = { "Model", "Rig", "Animation", "Materials" };

        internal const string VmdNotAutoGeneratedNotice =
            "PMX import does not auto-generate VMD or Timeline clips. " +
            "Create VMD Timeline clips from the MMD EditorWindow or the VMD Asset context menu.";

        public override void OnEnable()
        {
            base.OnEnable();
            importScaleProperty = serializedObject.FindProperty("importScale");
            modelPresetProperty = serializedObject.FindProperty("modelPreset");
            meshGenerationModeProperty = serializedObject.FindProperty("meshGenerationMode");
            materialTexturePolicyProperty = serializedObject.FindProperty("materialTexturePolicy");
            shaderPresetProperty = serializedObject.FindProperty("shaderPreset");
            materialRemapsProperty = serializedObject.FindProperty("materialRemaps");
            animationTypeProperty = serializedObject.FindProperty("animationType");
            ResolveImportedAsset();
        }

        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            MmdPmxAsset? asset = ResolveImportedAsset();

            selectedTab = GUILayout.Toolbar(selectedTab, TabNames);
            EditorGUILayout.Space();

            switch (selectedTab)
            {
                case 0:
                    DrawModelTab(asset);
                    break;
                case 1:
                    DrawRigTab(asset);
                    break;
                case 2:
                    DrawAnimationTab(asset);
                    break;
                case 3:
                    DrawMaterialTab(asset);
                    break;
            }

            serializedObject.ApplyModifiedProperties();
            ApplyRevertGUI();
        }

        private void DrawModelTab(MmdPmxAsset? asset)
        {
            if (modelPresetProperty != null)
            {
                EditorGUILayout.PropertyField(modelPresetProperty, new GUIContent("Model Preset"));
            }

            if (importScaleProperty != null)
            {
                EditorGUILayout.PropertyField(importScaleProperty,
                    new GUIContent("Import Scale",
                        "Scale applied to the imported PMX model. Stored as an import setting and asset summary. Scale-aware runtime instantiation is not applied yet."));
            }

            if (meshGenerationModeProperty != null)
            {
                EditorGUILayout.PropertyField(meshGenerationModeProperty,
                    new GUIContent("Mesh Generation",
                        "Mesh generation mode stored as an import setting. Normal PMX import still does not write generated Mesh assets; persistent split mesh export is available only through the explicit export workflow."));
            }

            if (asset != null)
            {
                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.TextField("Model", string.IsNullOrWhiteSpace(asset.ModelName) ? asset.name : asset.ModelName);
                    EditorGUILayout.IntField("Materials", asset.MaterialCount);
                    EditorGUILayout.IntField("Bones", asset.BoneCount);
                }
            }
            else
            {
                EditorGUILayout.HelpBox("Apply import settings to refresh the PMX asset.", MessageType.Warning);
            }

            bool hasModifiedImportSettings = HasModified();
            if (asset != null)
            {
                using (new EditorGUI.DisabledScope(asset.ByteLength == 0 || hasModifiedImportSettings))
                {
                    if (GUILayout.Button("Load PMX Into Scene"))
                    {
                        MmdEditorPmxLoader.LoadPmxIntoScene(asset);
                    }
                }

                DrawPendingImportSettingsWarning(hasModifiedImportSettings);
            }
        }

        private void DrawMaterialTab(MmdPmxAsset? asset)
        {
            DrawButtonRow("Textures", "Extract Textures...", enabled: false);

            if (asset != null)
            {
                EditorGUILayout.HelpBox(
                    "Materials are embedded inside the imported asset. Material assignments can be remapped below.",
                    MessageType.Info);
                DrawRemappedMaterials(asset);
            }
            else
            {
                EditorGUILayout.HelpBox("Apply import settings to refresh material data.", MessageType.Warning);
            }

            // Minimal Toon Shader Settings skeleton (UI only; backed by cached importer setting + PMX asset parse summary).
            // Placed after extract/remap surface, before pending warning. Does not parse PMX, does not write assets.
            toonShaderSettingsExpanded = EditorGUILayout.Foldout(
                toonShaderSettingsExpanded, "Toon Shader Settings", toggleOnLabelClick: true);
            if (toonShaderSettingsExpanded)
            {
                MmdPmxShaderPreset currentPresetForState = MmdPmxShaderPreset.MmdBasicUrpToon;
                if (shaderPresetProperty != null)
                {
                    EditorGUILayout.PropertyField(
                        shaderPresetProperty,
                        new GUIContent(
                            "Shader Preset",
                            "Selects the target shader family for material generation and Toon settings handoff. Only MmdBasicUrpToon is available in this slice. The value is an importer setting; it is summarized on the imported asset after Apply/Reimport. This UI is not a full Material Editor and does not mutate generated materials."));
                    currentPresetForState = (MmdPmxShaderPreset)shaderPresetProperty.enumValueIndex;
                }

                var state = BuildToonShaderSettingsState(asset, currentPresetForState);

                toonBasicExpanded = EditorGUILayout.Foldout(toonBasicExpanded, "Basic", toggleOnLabelClick: true);
                if (toonBasicExpanded)
                {
                    using (new EditorGUI.DisabledScope(true))
                    {
                        EditorGUILayout.TextField("Base / Diffuse Texture Readiness", state.BaseDiffuseTextureReadiness);
                        EditorGUILayout.IntField("PMX Material Count", state.MaterialCount);
                        EditorGUILayout.IntField("Transparent Material Count", state.TransparentMaterialCount);
                    }
                }

                toonShadingExpanded = EditorGUILayout.Foldout(toonShadingExpanded, "Shading", toggleOnLabelClick: true);
                if (toonShadingExpanded)
                {
                    using (new EditorGUI.DisabledScope(true))
                    {
                        EditorGUILayout.TextField("Toon Texture Readiness", state.ToonTextureReadiness);
                        EditorGUILayout.TextField("Sphere Texture Hint", state.SphereTextureHint);
                        EditorGUILayout.TextField("Shadow Step / Feather", state.ShadowStepFeather);
                        EditorGUILayout.TextField("Ambient / Direct Light Influence", state.AmbientDirectLightInfluence);
                    }
                }

                toonOutlineExpanded = EditorGUILayout.Foldout(toonOutlineExpanded, "Outline", toggleOnLabelClick: true);
                if (toonOutlineExpanded)
                {
                    using (new EditorGUI.DisabledScope(true))
                    {
                        EditorGUILayout.IntField("Edge Material Count", state.EdgeMaterialCount);
                        EditorGUILayout.TextField("Outline Pass Readiness", state.OutlinePassReadiness);
                        EditorGUILayout.TextField("Outline Width Scale", state.OutlineWidthScale);
                        EditorGUILayout.TextField("Outline Color Policy", state.OutlineColorPolicy);
                    }
                }

                toonAdvancedExpanded = EditorGUILayout.Foldout(toonAdvancedExpanded, "Advanced", toggleOnLabelClick: true);
                if (toonAdvancedExpanded)
                {
                    using (new EditorGUI.DisabledScope(true))
                    {
                        EditorGUILayout.TextField("Unsupported PMX Material Features", state.UnsupportedPmxMaterialFeatures);
                        EditorGUILayout.TextField("Shader Property Handoff Diagnostics", state.ShaderPropertyHandoffDiagnostics);
                    }
                }
            }

            // Read-only Material / Texture Persistence Policy status (static, policy-derived from the asset workflow boundary).
            // Follows Toon skeleton pattern: no PMX parse in OnInspectorGUI, no asset writes, asset param accepted for shape but policy values are hardcoded/static.
            // Placed after Toon foldout for Materials tab grouping; does not implement persistence.
            materialTexturePersistencePolicyExpanded = EditorGUILayout.Foldout(
                materialTexturePersistencePolicyExpanded, "Material / Texture Persistence Policy", toggleOnLabelClick: true);
            if (materialTexturePersistencePolicyExpanded)
            {
                var policyState = BuildMaterialTexturePersistencePolicyState(asset);

                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.TextField("Current Policy", policyState.CurrentPolicy);
                    EditorGUILayout.TextField("Material / Texture Persistence Implemented Now", policyState.ImplementedNow ? "true" : "false");
                    EditorGUILayout.IntField("Implemented Persistence Feature Count", policyState.ImplementedPersistenceFeatureCount);
                    EditorGUILayout.TextField("Source Texture Reference Policy", policyState.SourceReferencePolicy);
                    EditorGUILayout.TextField("Texture Copy / External Asset Write", policyState.TextureCopyExternalAssetWritePolicy);
                    EditorGUILayout.TextField("Normal Scene Placement Material Rule", policyState.NormalScenePlacementMaterialRule);
                }
            }

            DrawPendingImportSettingsWarning(HasModified());
        }

        private void DrawRigTab(MmdPmxAsset? asset)
        {
            // Animation Type selection (D2: Rig tab owns animation type).
            if (animationTypeProperty != null)
            {
                EditorGUILayout.PropertyField(animationTypeProperty,
                    new GUIContent("Animation Type",
                        "Controls how the imported model's bones map to Unity's animation system. " +
                        "Generic leaves bones as-is. Humanoid builds a Unity Avatar sub-asset " +
                        "via automatic MMD-to-Humanoid bone mapping."));
            }

            MmdPmxAnimationType currentType = MmdPmxAnimationType.Generic;
            if (animationTypeProperty != null)
            {
                currentType = (MmdPmxAnimationType)animationTypeProperty.enumValueIndex;
            }

            // When Humanoid, show bone mapping readiness.
            if (currentType == MmdPmxAnimationType.Humanoid && asset != null)
            {
                EditorGUILayout.Space();
                EditorGUILayout.LabelField("Humanoid Bone Mapping", EditorStyles.boldLabel);
                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.IntField("Bones", asset.BoneCount);
                    EditorGUILayout.TextField("Avatar Readiness", asset.HumanoidAvatarReadiness);
                    EditorGUILayout.ObjectField("Avatar", asset.ImportedAvatar, typeof(Avatar), allowSceneObjects: false);
                }

                if (asset.ImportedAvatar != null)
                {
                    EditorGUILayout.HelpBox(
                        "Avatar sub-asset is present. Reimport to rebuild it after bone changes.",
                        MessageType.Info);
                }
                else if (asset.BoneCount == 0)
                {
                    EditorGUILayout.HelpBox(
                        "No bones found. Avatar cannot be created for this model.",
                        MessageType.Warning);
                }
                else
                {
                    EditorGUILayout.HelpBox(
                        string.IsNullOrWhiteSpace(asset.HumanoidAvatarDiagnostic)
                            ? "Avatar sub-asset is not built yet. Apply/Reimport to generate it."
                            : asset.HumanoidAvatarDiagnostic,
                        MessageType.Info);
                }
            }
            else if (currentType != MmdPmxAnimationType.Humanoid && asset != null)
            {
                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.IntField("Bones", asset.BoneCount);
                }
            }
            else if (asset == null)
            {
                EditorGUILayout.HelpBox("Apply import settings to refresh rig data.", MessageType.Warning);
            }

            // Migration period: keep the old explicit button in an Advanced foldout.
            rigAdvancedExpanded = EditorGUILayout.Foldout(
                rigAdvancedExpanded, "Advanced (Migration)", toggleOnLabelClick: true);
            bool hasModifiedImportSettings = HasModified();
            if (rigAdvancedExpanded)
            {
                using (new EditorGUI.DisabledScope(asset == null || hasModifiedImportSettings))
                {
                    if (GUILayout.Button("Create Humanoid Setup Asset (Legacy)") && asset != null)
                    {
                        MmdHumanoidSetupAsset setup = MmdHumanoidSetupAssetBuilder.CreateHumanoidSetupAsset(
                            asset,
                            MmdHumanoidSetupAssetBuilder.GetDefaultSetupAssetPath(asset));
                        Selection.activeObject = setup;
                        EditorGUIUtility.PingObject(setup);
                    }
                }
            }

            DrawPendingImportSettingsWarning(hasModifiedImportSettings);
        }

        private void DrawAnimationTab(MmdPmxAsset? asset)
        {
            if (asset != null)
            {
                using (new EditorGUI.DisabledScope(true))
                {
                    EditorGUILayout.IntField("Bones", asset.BoneCount);
                }
            }
            else
            {
                EditorGUILayout.HelpBox("Apply import settings to refresh animation data.", MessageType.Warning);
            }

            bool hasModifiedImportSettings = HasModified();
            EditorGUILayout.Space();
            EditorGUILayout.HelpBox(VmdNotAutoGeneratedNotice, MessageType.Info);
            EditorGUILayout.Space();
            using (new EditorGUI.DisabledScope(asset == null || hasModifiedImportSettings))
            {
                if (GUILayout.Button("Create Prefab from PMX") && asset != null)
                {
                    MmdPmxPrefabExporter.CreatePrefabWithFeedback(asset);
                }
            }

            DrawPendingImportSettingsWarning(hasModifiedImportSettings);
        }

        private void DrawRemappedMaterials(MmdPmxAsset asset)
        {
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Remapped Materials", EditorStyles.boldLabel);
            onDemandRemapExpanded = EditorGUILayout.Foldout(onDemandRemapExpanded, "On Demand Remap", toggleOnLabelClick: true);
            if (!onDemandRemapExpanded)
            {
                return;
            }

            MmdPmxMaterialSummary[] materials = asset.MaterialSummaries;
            if (materials == null || materials.Length == 0)
            {
                EditorGUILayout.LabelField("No materials");
                return;
            }

            if (materialRemapsProperty == null)
            {
                return;
            }

            if (materialRemapsProperty.arraySize != materials.Length)
            {
                materialRemapsProperty.arraySize = materials.Length;
            }

            for (int i = 0; i < materials.Length; i++)
            {
                MmdPmxMaterialSummary material = materials[i];
                string materialName = string.IsNullOrWhiteSpace(material.name)
                    ? "Material " + material.index.ToString(System.Globalization.CultureInfo.InvariantCulture)
                    : material.name;
                SerializedProperty remap = materialRemapsProperty.GetArrayElementAtIndex(i);
                EditorGUILayout.PropertyField(remap, new GUIContent(materialName));
            }
        }

        private static bool DrawButtonRow(string label, string buttonLabel, bool enabled)
        {
            using (new EditorGUILayout.HorizontalScope())
            {
                EditorGUILayout.PrefixLabel(label);
                using (new EditorGUI.DisabledScope(!enabled))
                {
                    return GUILayout.Button(buttonLabel);
                }
            }
        }

        private static void DrawPendingImportSettingsWarning(bool hasModifiedImportSettings)
        {
            if (!hasModifiedImportSettings)
            {
                return;
            }

            EditorGUILayout.HelpBox(
                "Apply pending import setting changes before running asset-dependent actions.",
                MessageType.Warning);
        }

        private MmdPmxAsset? ResolveImportedAsset()
        {
            if (cachedAsset != null)
            {
                return cachedAsset;
            }

            cachedAsset = target is AssetImporter importer
                ? AssetDatabase.LoadAssetAtPath<MmdPmxAsset>(importer.assetPath)
                : null;
            return cachedAsset;
        }

        internal readonly struct ToonShaderSettingsState
        {
            public string ShaderPreset { get; }
            public int MaterialCount { get; }
            public int TransparentMaterialCount { get; }
            public int DiffuseTextureReferenceCount { get; }
            public int SphereTextureReferenceCount { get; }
            public int ToonTextureReferenceCount { get; }
            public int EdgeMaterialCount { get; }
            public string BaseDiffuseTextureReadiness { get; }
            public string ToonTextureReadiness { get; }
            public string SphereTextureHint { get; }
            public string ShadowStepFeather { get; }
            public string AmbientDirectLightInfluence { get; }
            public string OutlinePassReadiness { get; }
            public string OutlineWidthScale { get; }
            public string OutlineColorPolicy { get; }
            public string UnsupportedPmxMaterialFeatures { get; }
            public string ShaderPropertyHandoffDiagnostics { get; }

            public ToonShaderSettingsState(
                string shaderPreset,
                int materialCount,
                int transparentMaterialCount,
                int diffuseTextureReferenceCount,
                int sphereTextureReferenceCount,
                int toonTextureReferenceCount,
                int edgeMaterialCount,
                string baseDiffuseTextureReadiness,
                string toonTextureReadiness,
                string sphereTextureHint,
                string shadowStepFeather,
                string ambientDirectLightInfluence,
                string outlinePassReadiness,
                string outlineWidthScale,
                string outlineColorPolicy,
                string unsupportedPmxMaterialFeatures,
                string shaderPropertyHandoffDiagnostics)
            {
                ShaderPreset = string.IsNullOrWhiteSpace(shaderPreset) ? "MmdBasicUrpToon" : shaderPreset;
                MaterialCount = materialCount;
                TransparentMaterialCount = transparentMaterialCount;
                DiffuseTextureReferenceCount = diffuseTextureReferenceCount;
                SphereTextureReferenceCount = sphereTextureReferenceCount;
                ToonTextureReferenceCount = toonTextureReferenceCount;
                EdgeMaterialCount = edgeMaterialCount;
                BaseDiffuseTextureReadiness = baseDiffuseTextureReadiness ?? string.Empty;
                ToonTextureReadiness = toonTextureReadiness ?? string.Empty;
                SphereTextureHint = sphereTextureHint ?? string.Empty;
                ShadowStepFeather = shadowStepFeather ?? string.Empty;
                AmbientDirectLightInfluence = ambientDirectLightInfluence ?? string.Empty;
                OutlinePassReadiness = outlinePassReadiness ?? string.Empty;
                OutlineWidthScale = outlineWidthScale ?? string.Empty;
                OutlineColorPolicy = outlineColorPolicy ?? string.Empty;
                UnsupportedPmxMaterialFeatures = unsupportedPmxMaterialFeatures ?? string.Empty;
                ShaderPropertyHandoffDiagnostics = shaderPropertyHandoffDiagnostics ?? string.Empty;
            }
        }

        internal static ToonShaderSettingsState BuildToonShaderSettingsState(MmdPmxAsset? asset, MmdPmxShaderPreset preset)
        {
            string presetName = preset.ToString();

            if (asset == null)
            {
                string na = "N/A (pending Apply / import)";
                string noEdge = "No PMX draw-edge materials";
                return new ToonShaderSettingsState(
                    presetName,
                    materialCount: 0,
                    transparentMaterialCount: 0,
                    diffuseTextureReferenceCount: 0,
                    sphereTextureReferenceCount: 0,
                    toonTextureReferenceCount: 0,
                    edgeMaterialCount: 0,
                    baseDiffuseTextureReadiness: na,
                    toonTextureReadiness: na,
                    sphereTextureHint: na,
                    shadowStepFeather: "(placeholder)",
                    ambientDirectLightInfluence: "(placeholder)",
                    outlinePassReadiness: noEdge,
                    outlineWidthScale: "(placeholder)",
                    outlineColorPolicy: "(placeholder)",
                    unsupportedPmxMaterialFeatures: "none reported (UI skeleton)",
                    shaderPropertyHandoffDiagnostics: "not claimed (skeleton only)");
            }

            int mat = asset.MaterialCount;
            int trans = asset.TransparentMaterialCount;
            int diff = asset.DiffuseTextureReferenceCount;
            int sph = asset.SphereTextureReferenceCount;
            int toonRef = asset.ToonTextureReferenceCount;
            int edge = asset.EdgeMaterialCount;

            string baseReadiness = diff > 0
                ? $"{diff} PMX diffuse texture reference(s)"
                : "no diffuse texture references";
            string toonReadiness = toonRef > 0
                ? $"{toonRef} PMX toon texture reference(s)"
                : "no toon texture references";
            string sphereHint = sph > 0
                ? $"{sph} PMX sphere texture reference(s) (hint only)"
                : "no sphere texture references";

            string outlineReadiness = edge <= 0
                ? "No PMX draw-edge materials"
                : (preset == MmdPmxShaderPreset.MmdBasicUrpToon
                    ? "MmdBasicUrpToon outline pass"
                    : "Shader preset summary only");

            string unsupported = "none reported (UI skeleton)";
            string handoff = "not claimed (skeleton only; UI does not mutate generated materials)";

            return new ToonShaderSettingsState(
                presetName,
                mat,
                trans,
                diff,
                sph,
                toonRef,
                edge,
                baseReadiness,
                toonReadiness,
                sphereHint,
                "(placeholder)",
                "(placeholder)",
                outlineReadiness,
                "(placeholder)",
                "(placeholder)",
                unsupported,
                handoff);
        }

        internal readonly struct MaterialTexturePersistencePolicyState
        {
            public string CurrentPolicy { get; }
            public bool ImplementedNow { get; }
            public int ImplementedPersistenceFeatureCount { get; }
            public string SourceReferencePolicy { get; }
            public string TextureCopyExternalAssetWritePolicy { get; }
            public string NormalScenePlacementMaterialRule { get; }

            public MaterialTexturePersistencePolicyState(
                string currentPolicy,
                bool implementedNow,
                int implementedPersistenceFeatureCount,
                string sourceReferencePolicy,
                string textureCopyExternalAssetWritePolicy,
                string normalScenePlacementMaterialRule)
            {
                CurrentPolicy = currentPolicy ?? string.Empty;
                ImplementedNow = implementedNow;
                ImplementedPersistenceFeatureCount = implementedPersistenceFeatureCount;
                SourceReferencePolicy = sourceReferencePolicy ?? string.Empty;
                TextureCopyExternalAssetWritePolicy = textureCopyExternalAssetWritePolicy ?? string.Empty;
                NormalScenePlacementMaterialRule = normalScenePlacementMaterialRule ?? string.Empty;
            }
        }

        internal static MaterialTexturePersistencePolicyState BuildMaterialTexturePersistencePolicyState(MmdPmxAsset? asset)
        {
            // Policy is static and validator-backed.
            // asset is accepted to match Toon helper shape and allow null-asset call from tests/UI,
            // but is intentionally unused: no PMX parse, no asset-derived data for these claims,
            // no writes. OnInspectorGUI remains free of parse side effects.
            // Values make the P1 boundary explicit without claiming implementation.
            // Features: (1) importer Material sub-assets, (2) relative project Texture2D binding (no Texture sub-assets under .pmx).
            return new MaterialTexturePersistencePolicyState(
                currentPolicy: "importer Material sub-assets for normal placement; textures resolved to separate project Texture2D assets by PMX-relative path from .pmx location (no Texture sub-assets under .pmx); runtime texture-resolved materials remain raw-path/runtime fallback",
                implementedNow: true,
                implementedPersistenceFeatureCount: 2,
                sourceReferencePolicy: "PMX-relative / normalized string references remain source-of-truth/provenance; separate Unity Texture2D assets (when present under Assets/ next to PMX) are bound at import time",
                textureCopyExternalAssetWritePolicy: "no texture copy during normal import; external texture copy/export remains explicit opt-in only",
                normalScenePlacementMaterialRule: "normal placement must use importer Material sub-assets when present; material remaps override slots; textures come from separate imported assets via relative resolution");
        }
    }
}
